### ISSUE TITLE
CKAN URL is giving a 404

### ISSUE THREAD

**Issue by C-Loftus** [cgs-earth/pygeoapi-geoconnex-examples#1]
I believe the link in the href key for the link section of demo-ckan is giving a 404. This prevents the docker container from being spun up. If I remove it I can spin up pygeoapi.

Is there a better url to use for this instead?

**Comment by C-Loftus** [comment]
Weirdly, the pygeoapi container only fails for the CKAN block. I am now seeing that `              href: https://data.ca.gov/dataset/gsp-monitoring-data/resource/72612518-e45b-4900-9cab-72b8de09c57d
` is present in every collection in the config, so unclear if I am missing something

**Comment by ksonda** [comment]
lol they changed it. This is the main resource now https://data.ca.gov/dataset/gsp-monitoring-data

This is the specific table
https://data.ca.gov/dataset/gsp-monitoring-data/resource/ab3f524c-850f-40e4-b27a-6cae7154add5

also the `id_field:` is now evidently SITE_CODE
